# ðŸš€ CS:GO Initial ML (PyCaret)
This notebook aims at using PyCaret to model CS:GO players dataset.
First we use ``compare_model()`` method to evaluate a set of available methods.
Afterwards, we will use the best model to create a ML model and tune it.
Finally we report the results in the form of confusion matrix and basic metrics.

In [43]:
# Required Modluels
import os
import json
import pandas as pd
import pycaret

from collections import defaultdict

import pycaret
from pycaret.regression import *

# from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score


import sys
import platform
from datetime import date
print(f"  System: {sys.platform}")
print(f"  Python version: {platform.python_version()}")
print(f"  Last update: {date.today().strftime('%Y-%m-%d')}")

  System: darwin
  Python version: 3.11.8
  Last update: 2024-03-26

# ðŸ“Š Dataset
**Note:** The dataset used in this notebook is subject to change.

In [39]:
# Load dataset

# Paths to save
folder_model_path = f"models"
folder_eval_path = f"evaluation/metrics/"
folder_report_path = f"evaluation/reports"

folder_prediction_path = f"predictions"

# Path to load datasets
folder_data_ml_path = f"data/"
folder_processed_path = f"data/processed"


df = pd.read_csv(f"{folder_data_ml_path}/csgo_players.csv", low_memory=False)

df.head()

,player_id,nickname,real_name,age,country,current_team,teams,total_kills,total_deaths,headshot_percentage,...,3_kill_rounds,4_kill_rounds,5_kill_rounds,rifle_kills,sniper_kills,smg_kills,pistol_kills,grenade_kills,other_kills,rating
0,11893,ZywOo,Mathieu Herbaut,21,France,Vitality,"Vitality, aAa",22622,16458,41.2%,...,1474,369,71,8261,8552,1290,4262,260,49,1.32
1,7998,s1mple,Aleksandr Kostyliev,24,Ukraine,Natus Vincere,Natus Vincere,35512,26413,41.3%,...,2262,504,64,14717,13451,901,6057,199,254,1.25
2,16920,sh1ro,Dmitry Sokolov,21,Russia,Cloud9,"Gambit Youngsters, Gambit",18091,12492,27.8%,...,1075,221,30,3791,10580,550,3008,175,70,1.26
3,20113,deko,Denis Zhukov,21,Russia,1WIN,1WIN,8738,6397,36.7%,...,518,112,8,2664,4348,181,1459,86,40,1.23
4,18835,saffee,Rafael Costa,27,Brazil,FURIA,"FURIA, paiN",8482,6517,30.9%,...,524,114,14,2545,4412,264,1209,52,28,1.22

In [40]:
df.columns

Index(['player_id', 'nickname', 'real_name', 'age', 'country', 'current_team',
       'teams', 'total_kills', 'total_deaths', 'headshot_percentage',
       'damage_per_round', 'grenade_dmg_per_round', 'maps_played',
       'rounds_played', 'kills_per_death', 'kills_per_round',
       'assists_per_round', 'deaths_per_round', 'saved_by_teammate_per_round',
       'saved_teammates_per_round', 'rounds_with_kills', 'kill_to_death_diff',
       'total_opening_kills', 'total_opening_deaths', 'opening_kill_ratio',
       'opening_kill_rating', 'team_win_percent_after_first_kill',
       'first_kill_in_won_rounds', '0_kill_rounds', '1_kill_rounds',
       '2_kill_rounds', '3_kill_rounds', '4_kill_rounds', '5_kill_rounds',
       'rifle_kills', 'sniper_kills', 'smg_kills', 'pistol_kills',
       'grenade_kills', 'other_kills', 'rating'],
      dtype='object')

# ðŸ¤“ Preprocess Data
In this section, we will preprocess the dataset and get it ready for Machine Learning

In [34]:
#remove unneeded col's (stats)
cols_Remove = [0, 1, 2, 5, 6, 7, 8, 21, 22, 23, 25]
df = df.drop(df.columns[cols_Remove], axis=1)

#divide specific stats by rounds for normalization
cols_label_Divide = ["0_kill_rounds", "1_kill_rounds", "2_kill_rounds", "3_kill_rounds", "4_kill_rounds", "5_kill_rounds", "rifle_kills", "sniper_kills", "smg_kills", "pistol_kills", "grenade_kills", "other_kills"]

#Iterate over the columns and perform division
for col in cols_label_Divide:
    df[col] = df[col] / df["rounds_played"]
   
print(df.iloc[0])

age                                        21
country                                France
headshot_percentage                     41.2%
damage_per_round                         88.0
grenade_dmg_per_round                     3.6
maps_played                              1020
rounds_played                           26803
kills_per_death                          1.37
kills_per_round                          0.84
assists_per_round                        0.12
deaths_per_round                         0.61
saved_by_teammate_per_round               0.1
saved_teammates_per_round                0.12
rounds_with_kills                       14196
opening_kill_ratio                        1.6
team_win_percent_after_first_kill       73.1%
first_kill_in_won_rounds                21.4%
0_kill_rounds                        0.470358
1_kill_rounds                        0.305749
2_kill_rounds                        0.152483
3_kill_rounds                        0.054994
4_kill_rounds                        0.013767
5_kill_rounds                        0.002649
rifle_kills                          0.308212
sniper_kills                         0.319069
smg_kills                            0.048129
pistol_kills                         0.159012
grenade_kills                          0.0097
other_kills                          0.001828
rating                                   1.32
Name: 0, dtype: object

# ðŸŒŽ General ML models
In this section, we create an experiment to evaluate different models. To this end, we require to perform the following steps:
1. Create an experiment object
2. Create a setup dictionary and setup the environment
3. perfomt the model comparison
4. evaluate model to observe the initial performance

In [35]:
# Define PyCaret classificaiton experimetn
obj_exp = RegressionExperiment()

In [36]:
# Configure and build the setup environment
steup_dict= {
                "data": df,
                "fold": 10,
                "target": "rating",
                "index": True,
                "session_id": 420,
                "experiment_name": "experiment_csgo_initial",
                "normalize": True,
                "normalize_method": "zscore",
                "verbose": True
            }

obj_exp.setup(**steup_dict)

In [37]:
# Perform the model comparison
best = obj_exp.compare_models()

In [38]:
obj_exp.evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

# âœ… Best ML Model
In this section we use the ML model obtained from the previous step to:
1. Create the model
2. Tune the model
3. Finalize the model
4. Evaluate the model performance (metrics)